#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

red='\033[0;31m'

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|merge|wip)(\(.+?\))?: .{1,}$"; then
    echo "🔨❌ ${red} Aborting commit. Your commit message is invalid. Please use yarn commit for better commits...🔨❌" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,120}$"; then
    echo "🔨❌${red} Aborting commit. Your commit message is too long.🔨❌" >&2
    exit 1
fi
